on:
  push:
    branches:
      - stage

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: docker run -i --rm -v $(pwd):/root/server -w /root/server gradle:6.3-jdk11 gradle clean test
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: test reports
          path: ./build/reports
